[package]
name = "planck-universe"
version = "0.0.2"
edition = "2021"
description = "an experiment in physics"
license = "MIT"

[dependencies]
bevy = { version = "0.15.3", features = ["dynamic_linking"] }
num-bigint = "0.4.6"
rust_decimal = "1.37.2"
